### PR TITLE
Update to sigaws_otp_24

### PR DESCRIPTION
**Pull request by LetThereBeDwight**
This is in reference to #98 - I've forked the sigaws repo and published it to hex with the changes from the PR seen [here](https://github.com/handnot2/sigaws/pull/12)

### CODE REVIEW

**Comment by prem-prakash** [comment]
@danielberkompas can we merge this?

**Comment by LetThereBeDwight** [comment]
@danielberkompas Any chance we can take a look at merging this?

**Comment by danielberkompas** [comment]
Apologies for the very long delay here. I'll merge it.

**Comment by prem-prakash** [comment]
better late than never, thanks

**Pull request merged**
